### ISSUE TITLE
Some images are missing

### ISSUE THREAD

**Issue by glmagalhaes** [dereknex/vscode-openapi-viewer#1]
First. Your plug-in is really helpful.

The padlock icon that state that a path need authorization ins't showing.

![captura de tela de 2018-05-21 17-09-11](https://user-images.githubusercontent.com/5274195/40327609-f100cb96-5d19-11e8-9801-cd285ae12ee5.png)

Also the close image when you are in the authorization pop-up isn't showing either

![captura de tela de 2018-05-21 17-09-11](https://user-images.githubusercontent.com/5274195/40327569-d5a5a3ee-5d19-11e8-9f4f-166ea33d3472.png)

Other images may also be missing.

**Comment by dereknex** [comment]
@glmagalhaes Plz upgrade to v0.1.5.
